# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='qname',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
