# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_remove_quotemodel_quser'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='quser',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
