# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_auto_20170125_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='qname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='quote',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
