# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0005_quotemodel_quser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='quser',
            field=models.CharField(max_length=25),
        ),
    ]
