# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0005_auto_20170127_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='qname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='quote',
            field=models.CharField(max_length=150),
        ),
    ]
