# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0009_auto_20170216_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='userquotes',
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='userquotes',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='quoteapp.UserModel'),
            preserve_default=False,
        ),
    ]
