# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0010_auto_20170217_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='userquotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quoteapp.UserModel'),
        ),
    ]
