# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0012_auto_20170217_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotemodel',
            old_name='userquotes',
            new_name='quser',
        ),
    ]
