# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quoteapp', '0013_auto_20170217_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quotemodel',
            name='quser',
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='userquotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
