# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0014_auto_20170217_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='userquotes',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
